// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIcSCn7nZ4_UA9vpkN4PcSVBkyq6Y48Pw',
    appId: '1:863349911759:web:fca323c04e2a47085187ba',
    messagingSenderId: '863349911759',
    projectId: 'rvcehackathon',
    authDomain: 'rvcehackathon.firebaseapp.com',
    storageBucket: 'rvcehackathon.appspot.com',
    measurementId: 'G-FNMJTCV1PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKHijyV345zvrgrlUKGp5UUKBhUEEzaOE',
    appId: '1:863349911759:android:584d567bca10986f5187ba',
    messagingSenderId: '863349911759',
    projectId: 'rvcehackathon',
    storageBucket: 'rvcehackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJVjhdXTdrjrcHQyMMtnmP9npp0YE_PBU',
    appId: '1:863349911759:ios:0f38837d84254af75187ba',
    messagingSenderId: '863349911759',
    projectId: 'rvcehackathon',
    storageBucket: 'rvcehackathon.appspot.com',
    iosClientId: '863349911759-97vbqg7og0e7oegp9dh7oaqrln2thtfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.dreampath',
  );
}
